import {
    AboutSlint,
    Button,
    VerticalBox,
    ProgressIndicator,
    Spinner,
    Palette,
    StyleMetrics,
    HorizontalBox,
    LineEdit,
} from "std-widgets.slint";


export enum Interval {
    Focus, ShortBreak, LongBreak
}

struct Message {
    summary: string,
    body: string,
}

export global ExternalSystem {
    // default values
    in-out property <int> focus_duration: 1500; // 25 minutes
    in-out property <int> short_break_duration: 300; // 5 minutes
    in-out property <int> long_break_duration: 1200; // 20 minutes
    in-out property <int> sessions: 4;

    callback notify(message: Message);
    callback save_focus(value: int);
    callback save_short_break(value: int);
    callback save_long_break(value: int);
    callback save_sessions(value: int);
    callback update_progress(progress: float);
    callback stop_progress();
}

export global System {
    // global values
    in-out property <Interval> status: Interval.Focus;
    in-out property <int> value: System.getDuration(status);
    in-out property <bool> started: false;
    in-out property <int> sessionCount: 1;
    in-out property <bool> running: false;

    out property <[Message]> focus_messages: [
        {
            summary: "Interval Ended",
            body: "Time for a breather! Hydrate with some water and stretch a bit"
        },
        {
            summary: "Interval Ended",
            body: "Great work! Stand up, walk around, or do a few quick exercises to recharge"
        },
        {
            summary: "Interval Ended",
            body: "Step away from the screen; perhaps grab a drink or stretch"
        },
        {
            summary: "Interval Ended",
            body: "Break time! How about a short walk or some light stretching to clear your head?"
        },
    ];
    out property <[Message]> short_break_messages: [
        { summary: "Break Ended", body: "Time to focus again! Keep up the good work!" },
        { summary: "Break Ended", body: "Great job! Let's get back to work!" },
        { summary: "Break Ended", body: "Ready to dive back in? Let's go!" },
        { summary: "Break Ended", body: "Focus time again. You got this!" },
    ];
    out property <[Message]> long_break_messages: [
        {
            summary: "Break Ended",
            body: "Time to get back to it. You're refreshed and ready!"
        },
        { summary: "Break Ended", body: "Long break's done. What's next on your to-do list?" },
        { summary: "Break Ended", body: "Feeling recharged? Let's finish strong!" },
        { summary: "Break Ended", body: "Focus time again. You got this!" },
    ];
    in-out property <int> message_count: 0;

    pure public function getDuration(counter: Interval) -> int {
        if (counter == Interval.Focus) {
            // return 1500; // 25 minutes
            return ExternalSystem.focus_duration;
        } else if (counter == Interval.ShortBreak) {
            // return 300; // 5 minutes
            return ExternalSystem.short_break_duration;
        } else {
            // return 1200; // 20 minutes
            return ExternalSystem.long_break_duration;
        }
    }

    pure function nextMessage(finished_interval: Interval) -> Message {
        if finished_interval == Interval.Focus {
            return System.focus_messages[mod(System.sessionCount, 3)];
        } else if finished_interval == Interval.ShortBreak {

            return System.short_break_messages[mod(System.sessionCount, 3)];
        } else if finished_interval == Interval.LongBreak {

            return System.long_break_messages[mod(System.sessionCount, 3)];
        }
        return { summary: "Error", body: "Unexpected interval detected" };
    }

    public function next() {
        if System.status == Interval.Focus {
            System.sessionCount = System.sessionCount + 1;
        }
        ExternalSystem.notify(nextMessage(System.status));
        System.status = System.nextInterval(System.status, System.sessionCount);
        System.value = System.getDuration(System.status);
        ExternalSystem.stop_progress();
    }

    pure function nextInterval(interval: Interval, sessionCount: int) -> Interval {
        if (interval == Interval.LongBreak || interval == Interval.ShortBreak) {
            return Interval.Focus;
        } else if (interval == Interval.Focus) {
            if (mod(sessionCount, 5) == 0) {
                return Interval.LongBreak;
            } else {
                return Interval.ShortBreak;
            }
        }
        return Interval.Focus;
    }

    public function toggleStart() {
        if System.value > 0 {
            System.running = !System.running;
        }
        // Only on start we set the started variable to true
        if (!System.started) {
            System.started = true;
        }
    }
    public function reset() {
        System.status = Interval.Focus;
        System.sessionCount = 1;
        System.value = System.getDuration(Interval.Focus);
        System.running = false;
        System.started = false;
        ExternalSystem.stop_progress();
    }
}

export component Pomodoro {
    callback navigate(page: int);

    pure function intervalToString(interval: Interval) -> string {
        if (interval == Interval.Focus) {
            return "Focus";
        } else if (interval == Interval.ShortBreak) {
            return "Short Break";
        } else {
            return "Long Break";
        }
    }

    pure function displayTime(seconds: int) -> string {
        floor(seconds / 60) + ":" + (mod(seconds, 60) / 1 < 10 ? "0" : "") + floor(mod(seconds, 60) / 1)
    }

    VerticalBox {

        alignment: center;
        spacing: 20px;

        HorizontalBox {
            alignment: end;

            Button {
                icon: @image-url("./icons/settings.svg");
                colorize-icon: true;
                clicked() => {
                    navigate(1);
                }
            }
        }

        HorizontalBox {
            alignment: center;
            Text {
                text: intervalToString(System.status);
                font-size: 20pt;
            }
        }

        HorizontalBox {
            alignment: center;
            VerticalBox {
                Text {
                    text: displayTime(System.value);
                    font-size: 40pt;
                    color: Palette.accent-background;
                    font-weight: 600;
                }
            }
        }

        ProgressIndicator {
            progress: 1 - System.value / System.getDuration(System.status);
        }

        HorizontalBox {
            alignment: center;
            Text {
                visible: System.status == Interval.Focus;
                text: "Session " + System.sessionCount;
            }
        }

        HorizontalBox {
            alignment: center;
            spacing: 5px;
            Button {
                text: System.running ? "Pause" : System.started ? "Continue" : "Start";
                icon: System.running ? @image-url("./icons/pause.svg") : @image-url("./icons/play.svg");
                colorize-icon: true;
                primary: true;
                clicked() => {
                    System.toggleStart();
                }
            }

            Button {
                text: "Reset";
                icon: @image-url("./icons/reset.svg");
                colorize-icon: true;

                enabled: System.started;
                clicked() => {
                    System.reset();
                }
            }

            Button {
                text: "Skip";
                icon: @image-url("./icons/skip.svg");
                colorize-icon: true;
                enabled: System.started;
                clicked() => {
                    System.next();
                }
            }
        }
    }
}

export component Settings {
    callback navigate(page: int);

    key-handler-set := FocusScope {
        key-pressed(event) => {
            if (event.text == "b") {
                navigate(0);
            }
            accept
        }
    }

    VerticalBox {
        alignment: space-between;

        HorizontalBox {
            alignment: start;
            Button {
                icon: @image-url("./icons/left.svg");
                clicked() => {
                    navigate(0);
                }
            }
        }

        VerticalLayout {
            spacing: 5px;
            Text {
                text: "Interval duration";
            }

            HorizontalLayout {

                LineEdit {
                    placeholder-text: "Interval duration";
                    input-type: number;
                    text: ExternalSystem.focus_duration / 60;
                    width: 50%;
                    edited(text) => {
                        ExternalSystem.focus_duration = text.to-float() * 60;
                        ExternalSystem.save_focus(ExternalSystem.focus_duration);
                    }
                }
            }
        }

        VerticalLayout {
            spacing: 5px;
            Text {
                text: "Short break duration";
            }

            LineEdit {
                placeholder-text: "Short break duration";
                input-type: number;
                text: ExternalSystem.short_break_duration / 60;
                edited(text) => {
                    ExternalSystem.short_break_duration = text.to-float() * 60;
                    ExternalSystem.save_focus(ExternalSystem.short_break_duration);
                }
            }
        }

        VerticalLayout {
            spacing: 5px;
            Text {
                text: "Long break duration";
            }

            LineEdit {
                placeholder-text: "Long break duration";
                input-type: number;
                text: ExternalSystem.long_break_duration / 60;
                edited(text) => {
                    ExternalSystem.long_break_duration = text.to-float() * 60;
                    ExternalSystem.save_focus(ExternalSystem.long_break_duration);
                }
            }
        }

        VerticalLayout {
            spacing: 5px;
            Text {
                text: "Sessions before long break";
            }

            LineEdit {
                placeholder-text: "Sessions before long break";
                input-type: number;
                text: ExternalSystem.sessions;
                edited(text) => {
                    ExternalSystem.sessions = text.to-float() * 60;
                    ExternalSystem.save_focus(ExternalSystem.sessions);
                }
            }
        }
    }
}

export component AppWindow inherits Window {
    min-width: 300px;
    min-height: 450px;
    icon: @image-url("./icons/logo.svg");
    title: "Temporis";

    in-out property <int> current_page: 0;

    function navigate(page: int) {
        root.current_page = page;
    }

    timer := Timer {
        interval: 1s;
        running: System.running;
        triggered() => {
            System.value -= 1;
            // Update progress every 10 seconds
            if (mod(System.value, 10) == 0) {
                ExternalSystem.update_progress(1 - System.value / System.getDuration(System.status));
            }
            if (System.value == 0) {
                System.next()
            }
        }
    }

    key-handler := FocusScope {
        key-pressed(event) => {
            debug(event.text);
            if (event.text == "s") {
                System.toggleStart();
            }
            if (event.text == "r") {
                System.reset();
            }
            if (event.text == "k") {
                System.next();
            }
            if (event.text == "c") {
                navigate(1);
            }
            if (event.text == "b") {
                navigate(0);
            }
            accept
        }
    }

    if (root.current_page == 0): Pomodoro {
        navigate(page) => {
            root.current_page = page;
        }
    }
    if (root.current_page == 1): Settings {
        navigate(page) => {
            root.current_page = page;
        }
    }
}
