name: "Website"
on:
  push:
    branches:
      - main

jobs:
  deploy-website:
    if: "startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v7
      - name: Install nix
        uses: cachix/install-nix-action@v31
      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
      - name: Build site package
        run: |
          nix build .#site -o dist
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
